version: '3'

services:
  flask-api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - nextjs-frontend

  nextjs-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
